debian/baldurs-gate-2.cfg       etc/gemrb/
debian/baldurs-gate-2.desktop   usr/share/applications/
debian/icons/baldurs-gate-2.svg usr/share/icons/hicolor/scalable/apps/
debian/icons/baldurs-gate-2.png usr/share/pixmaps/

debian/baldurs-gate-2-tob.cfg       etc/gemrb/
debian/baldurs-gate-2-tob.desktop   usr/share/applications/
debian/icons/baldurs-gate-2-tob.svg usr/share/icons/hicolor/scalable/apps/
debian/icons/baldurs-gate-2-tob.png usr/share/pixmaps/
