debian/icewind-dale.cfg       etc/gemrb/
debian/icewind-dale.desktop   usr/share/applications/
debian/icons/icewind-dale.svg usr/share/icons/hicolor/scalable/apps/
debian/icons/icewind-dale.png usr/share/pixmaps/

debian/icewind-dale-how.cfg       etc/gemrb/
debian/icewind-dale-how.desktop   usr/share/applications/
debian/icons/icewind-dale-how.svg usr/share/icons/hicolor/scalable/apps/
debian/icons/icewind-dale-how.png usr/share/pixmaps/
